# fly.toml app configuration file generated for yamanoyamanote on 2023-05-28T20:13:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yamanoyamanote"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[[mounts]]
  source = "senofyamanote"
  destination = "/mnt/senofyamanote"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
